// examples/vue/src/App.vue
<template>
  <input v-model="search" />
  <DataTable
    :headers="headers"
    :items="items"
    :search="search"
    :pagination="[1, 2, 'ALL']"
  />
</template>

<script setup lang="ts">
import type { Header, Item } from '@miyauci/vue-data-table'
import { ref } from 'vue'
const headers: Header[] = [
  {
    text: 'hoge',
    value: 'name'
  },
  {
    text: 'fsf',
    value: 'hogsg'
  }
]
const items: Item[] = [
  { name: 1, hogsg: '1213' },
  { name: 22, hogsg: 'ffff' },
  { name: 1, hogsg: '1213' }
]
const search = ref('')
</script>

// packages/react/src/App.tsx
import React, { FC, ChangeEvent, useState } from 'react'
import DataTable from './components/DataTable'
import type { Item, Header } from '@miyauci/data-table-core'

const App: FC = () => {
  const headers: Header[] = [
    {
      text: 'Name',
      value: 'hoge'
    }
  ]
  const items: Item[] = [
    {
      hoge: 'huga'
    }
  ]

  const [search, setSearch] = useState('')

  const handleChange = ({
    target: { value }
  }: ChangeEvent<HTMLInputElement>): void => {
    setSearch(value)
  }

  return (
    <div className="App">
      <input onChange={handleChange} value={search} />
      <DataTable headers={headers} items={items} search={search} />
    </div>
  )
}

export default App
